"""Password hashing and JWT issuance.

Passwords use Argon2id, the current OWASP recommendation. Argon2 is memory-hard,
which makes GPU-based cracking far more expensive than it is against bcrypt.

Refresh tokens are stored only as SHA-256 hashes. A database leak therefore
does not hand an attacker usable sessions.
"""

import hashlib
import secrets
import uuid
from datetime import UTC, datetime, timedelta
from typing import Any, Literal

import jwt
from argon2 import PasswordHasher
from argon2.exceptions import InvalidHashError, VerifyMismatchError

from app.core.config import get_settings

_settings = get_settings()

# Defaults follow the argon2-cffi maintainers' recommended profile.
_hasher = PasswordHasher()

TokenType = Literal["access", "refresh"]


class TokenError(Exception):
    """Raised when a token is missing, malformed, expired, or the wrong type."""


# ---------------------------------------------------------------------------
# Passwords
# ---------------------------------------------------------------------------


def hash_password(plain: str) -> str:
    return _hasher.hash(plain)


def verify_password(plain: str, hashed: str) -> bool:
    """Constant-time-ish verification. Never raises on a wrong password."""
    try:
        _hasher.verify(hashed, plain)
    except (VerifyMismatchError, InvalidHashError, ValueError):
        return False
    return True


def needs_rehash(hashed: str) -> bool:
    """True when a stored hash predates the current cost parameters.

    Call after a successful login to transparently upgrade old hashes.
    """
    try:
        return _hasher.check_needs_rehash(hashed)
    except (InvalidHashError, ValueError):
        return False


# ---------------------------------------------------------------------------
# JWTs
# ---------------------------------------------------------------------------


def _create_token(
    subject: uuid.UUID,
    token_type: TokenType,
    expires_delta: timedelta,
    extra_claims: dict[str, Any] | None = None,
) -> str:
    now = datetime.now(UTC)
    payload: dict[str, Any] = {
        "sub": str(subject),
        "typ": token_type,
        "iat": int(now.timestamp()),
        "exp": int((now + expires_delta).timestamp()),
        # Unique id so a specific token can be revoked or traced in audit logs.
        "jti": secrets.token_urlsafe(16),
    }
    if extra_claims:
        payload.update(extra_claims)
    return jwt.encode(payload, _settings.jwt_secret, algorithm=_settings.jwt_algorithm)


def create_access_token(
    user_id: uuid.UUID, roles: list[str] | None = None
) -> str:
    """Short-lived token.

    Roles are embedded for cheap coarse checks, but they are NOT the
    authorization source of truth — every student-data query still resolves
    through the visibility layer against live database state. A role removed in
    the database takes effect immediately there, without waiting for this token
    to expire.
    """
    return _create_token(
        user_id,
        "access",
        timedelta(minutes=_settings.access_token_ttl_minutes),
        {"roles": roles or []},
    )


def create_refresh_token(user_id: uuid.UUID) -> str:
    return _create_token(
        user_id, "refresh", timedelta(days=_settings.refresh_token_ttl_days)
    )


def decode_token(token: str, expected_type: TokenType) -> dict[str, Any]:
    """Decode and validate a token, or raise TokenError.

    Signature, expiry, and token type are all checked. The type check prevents
    a refresh token from being presented as an access token.
    """
    try:
        payload = jwt.decode(
            token,
            _settings.jwt_secret,
            algorithms=[_settings.jwt_algorithm],
            options={"require": ["exp", "sub", "typ"]},
        )
    except jwt.ExpiredSignatureError as exc:
        raise TokenError("Token has expired") from exc
    except jwt.InvalidTokenError as exc:
        raise TokenError("Token is invalid") from exc

    if payload.get("typ") != expected_type:
        raise TokenError(
            f"Expected a {expected_type} token, got {payload.get('typ')!r}"
        )
    return payload


def token_subject(payload: dict[str, Any]) -> uuid.UUID:
    try:
        return uuid.UUID(payload["sub"])
    except (KeyError, ValueError) as exc:
        raise TokenError("Token subject is not a valid user id") from exc


# ---------------------------------------------------------------------------
# Refresh-token storage
# ---------------------------------------------------------------------------


def hash_refresh_token(token: str) -> str:
    """SHA-256 of the raw token, for storage in refresh_tokens.token_hash.

    A fast hash is correct here: the token is 100+ bits of entropy generated by
    us, so it is not brute-forceable the way a human-chosen password is, and
    lookups happen on every refresh.
    """
    return hashlib.sha256(token.encode("utf-8")).hexdigest()
